"""Update Date Consults

Revision ID: 62bf585445da
Revises: fca54bf31530
Create Date: 2025-09-10 16:31:09.517408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bf585445da'
down_revision = 'fca54bf31530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_consult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_consult', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
