"""Update emergency

Revision ID: fca54bf31530
Revises: 1bf8e06ff3af
Create Date: 2025-09-10 03:35:41.560081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca54bf31530'
down_revision = '1bf8e06ff3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_sos', schema=None) as batch_op:
        batch_op.alter_column('nurse_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_sos', schema=None) as batch_op:
        batch_op.alter_column('nurse_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
